package uz.codebyz.message.domain;

public enum EventType {
    MESSAGE_CREATED,
    MESSAGE_EDITED,
    MESSAGE_DELETED,
    MESSAGE_READ,
    MESSAGE_REACTION_ADDED,
    MESSAGE_REACTION_REMOVED,
    SYSTEM_MESSAGE_CREATED,
    USER_TYPING_START,
    USER_TYPING_STOP,
    USER_ONLINE,
    USER_OFFLINE,
    CHAT_BLOCKED,
    CHAT_UNBLOCKED,
    ERROR,
    EVENT_ACK
}
