package uz.codebyz.auth.common;

public enum ErrorCode {
    VALIDATION_ERROR,
    USER_NOT_FOUND,
    USER_DISABLED,
    EMAIL_NOT_VERIFIED,
    BAD_CREDENTIALS,
    USERNAME_TAKEN,
    EMAIL_TAKEN,
    VERIFICATION_NOT_FOUND,
    VERIFICATION_EXPIRED,
    VERIFICATION_INVALID,
    VERIFICATION_USED,
    DEVICE_ID_REQUIRED,
    DEVICE_LIMIT_EXCEEDED,
    LOGIN_BLOCKED,
    LOCATION_LOOKUP_FAILED,
    FILE_SAVE_ERROR, INVALID_FILE, FILE_REQUIRED,
    SAME_PASSWORD,
    INVALID_PASSWORD,
    PASSWORD_WEAK,
    NEW_PASSWORD_REQUIRED,
    OLD_PASSWORD_REQUIRED,
    INVALID_TOKEN, TOKEN_EXPIRED, UNAUTHORIZED, FORBIDDEN, BAD_REQUEST, INTERNAL_ERROR
}
